spring:
  application:
    name: restaurant-service
  config:
    import: optional:classpath:config/platform-defaults.yml,optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cache:
    type: redis
    redis:
      time-to-live: 1h
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids: true
resilience4j:
  retry:
    instances:
      kycApiRetry:
        maxAttempts: 3
        waitDuration: 2s
      wallet-service:
        baseConfig: default
      government-id-service:
        baseConfig: default
      customer-service:
        baseConfig: default
      advertisement-service:
        baseConfig: default
      delivery-service:
        baseConfig: default
  circuitbreaker:
    instances:
      kycApiCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
      wallet-service:
        baseConfig: default
      government-id-service:
        baseConfig: default
      customer-service:
        baseConfig: default
      advertisement-service:
        baseConfig: default
      delivery-service:
        baseConfig: default
  timelimiter:
    instances:
      wallet-service:
        baseConfig: default
      government-id-service:
        baseConfig: default
      customer-service:
        baseConfig: default
      advertisement-service:
        baseConfig: default
      delivery-service:
        baseConfig: default
