apiVersion: v1
kind: Secret
metadata:
  name: food-delivery-secrets
  namespace: food-delivery-prod
type: Opaque
stringData:
  DB_PASSWORD: "CHANGE_ME_IN_PROD_VAULT"
  VYAPAR_API_KEY: "CHANGE_ME_IN_PROD_VAULT"
  VYAPAR_SECRET: "CHANGE_ME_IN_PROD_VAULT"
  OLA_MAPS_API_KEY: "CHANGE_ME_IN_PROD_VAULT"
