ALTER TABLE outlets
ADD COLUMN cuisine VARCHAR(255),
ADD COLUMN rating NUMERIC(3, 1) DEFAULT 0.0,
ADD COLUMN reviews_count INTEGER DEFAULT 0,
ADD COLUMN delivery_time INTEGER,
ADD COLUMN delivery_fee NUMERIC(10, 2),
ADD COLUMN tags TEXT;
